temp: try to compile all apps

diff --git a/.github/workflows/cached-golang-ecr-image-managed.yaml b/.github/workflows/cached-golang-ecr-image-managed.yaml
--- a/.github/workflows/cached-golang-ecr-image-managed.yaml
+++ b/.github/workflows/cached-golang-ecr-image-managed.yaml
@@ -151,8 +151,11 @@ jobs:
       - name: Go Cache Download & Build All
         if: steps.go-cache-restore.outputs.cache-hit != 'true'
         run: |
-          go mod download
-          make ci-build-${{ inputs.fetcher-name != '' && inputs.fetcher-name || inputs.app-name }} VERSION=${{ steps.vars.outputs.tag }} BUILD_TIME=${{ steps.vars.outputs.date }} COMMIT_SHA=${GITHUB_SHA} WORK_DIR=${GITHUB_WORKSPACE}
+          for target in $(make -pRrq | grep -oP '^ci-build-[^ :]*' | sort -u); do
+                make "$target" || echo "Skipping failed target: $target"
+          done
+          #go mod download
+          #make ci-build-${{ inputs.fetcher-name != '' && inputs.fetcher-name || inputs.app-name }} VERSION=${{ steps.vars.outputs.tag }} BUILD_TIME=${{ steps.vars.outputs.date }} COMMIT_SHA=${GITHUB_SHA} WORK_DIR=${GITHUB_WORKSPACE}
   build-push-ecr:
     name: "Build & Push ECR Docker Image "
     environment: ${{ inputs.environment }}
